version: "3"
services:
  postgres:
    image: postgres:10.5
    networks:
      - network
    hostname: postgres
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "waterlooquestplus"
  api:
    image: tylerzhang/waterlooquestplus:0.2
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/waterlooquestplus"
      DATABASE_SYNC: 1
    ports:
      - "3000:80"
    networks:
      - network
    depends_on:
      - postgres
    hostname: api
networks:
  network:
    driver: bridge
